### ISSUE TITLE
Composer installation failure with PHP 8

### ISSUE THREAD

**Issue by nabilanam** [devfaysal/laravel-bangladesh-geocode#1]
Problem 1
    - devfaysal/laravel-bangladesh-geocode is locked to version 0.5.1 and an update of this package was not requested.  
    - devfaysal/laravel-bangladesh-geocode 0.5.1 requires php ^7.3 -> your php version (8.0.0) does not satisfy that requirement.

**Comment by devfaysal** [comment]
Added PHP 8 in `composer.json` and released a new version.
Try now and let me know if all working fine.

**Comment by nabilanam** [comment]
It's working
