### ISSUE TITLE
Good but information missing

### ISSUE THREAD

**Issue by ashique12009** [devfaysal/laravel-bangladesh-geocode#3]
Divisions, upazila and union do not have longitude and latitude information.
From where you collected these information?
Thanks.

**Comment by devfaysal** [comment]
Yeah, not everything has lat/long info right now.
All information collected from https://github.com/nuhil/bangladesh-geocode
There is a note about it in the [readme](https://github.com/devfaysal/laravel-bangladesh-geocode#credits).
